### ISSUE TITLE
Recurring Transaction Dates Don't Match

### ISSUE THREAD

**Issue by LadyMopar** [Ledger-Software/Ledger#278]
If I add a recurring transaction and I enter a start and end date in May, when I go to the Recurring Editor, it shows up as April. Likewise if I set it to occur in April, it'll show up in March. It's always one month behind.
![image](https://cloud.githubusercontent.com/assets/10874723/25720171/f4ab8d84-30d9-11e7-909b-b456ca8a10e3.png)
![image](https://cloud.githubusercontent.com/assets/10874723/25720194/0b26162e-30da-11e7-9ca2-6486770c9fb2.png)

**Comment by taylerhow** [comment]
Something to add: I created two recurring transactions.
The first was for -$5 and was originally set to run daily from May 1 - May 8. In the editor, the dates were displayed as April 1 - April 8, as Emily pointed out.
The second was for -$2 and was originally set to run daily from June 1 - June 8. In the editor, the dates were displayed as May 1 - May 8.

Then, I logged out and back in to the app to see if either of the recurring transactions would trigger. It turns out the first one did, for -$5. So it seems that the dates are being set correctly in the backend, but not displayed correctly in the editor.

![image](https://cloud.githubusercontent.com/assets/10555067/25747175/8f46a0e6-3174-11e7-8d82-435c19899284.png)

**Comment by taylerhow** [comment]
Fun fact, if you create a recurrence with the dates May 1 - May 31, launching the Recurring Transaction editor will crash, as "April 31" is not a valid date (since April only has 30 days).

![image](https://cloud.githubusercontent.com/assets/10555067/25771530/4a439ed2-3222-11e7-8e4f-8f442c3a1faf.png)

**Comment by shellajt** [comment]
Opened PR #298 to address this

**Comment by shellajt** [comment]
PR merged
